map $uri $redirect_target {
    default "";
    include /etc/nginx/conf.d/redirects.map;
}

server {
    listen 80;
    server_name localhost _;
    
    root /usr/share/nginx/html;    

    location / {
        if ($redirect_target) {
            return 302 $redirect_target$is_args$args; # Use 301 for permanent redirects if appropriate in production
        }

        try_files $uri $uri/ /index.html;
    }
}
